### DISCUSSION TITLE
Echot Dot not announcing

### DISCUSSION THREAD

**Discussion by oudoulj** [chemelli74/aioamazondevices#229] [Q&A] [answered]
I am running **Home Assistant 2025.6.0b5**
I have the following automation (inspired by the example [here](https://rc.home-assistant.io/integrations/amazon_devices#automation-announce-welcome-when-you-arrive-home)) triggered by an Aqara mini switch but no announcement comes out on my Echot Dot 4 with clock :crying_cat_face: 
There are no errors in the traces and the volume is up :man_shrugging: 
Did I miss something?
Anyone else experiencing this?
NB: I have also tried with Play B.B.C. on Tunein as a message to no avail...

```
alias: Alexa announce
description: Alexa announce
triggers:
  - device_id: 2ff14c779a5287c4e9079af97ce9ba5d
    domain: deconz
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
actions:
  - action: notify.send_message
    data:
      message: Welcome home Jerome
    target:
      entity_id: notify.office_announce
mode: single
```

![image](https://github.com/user-attachments/assets/92683363-5850-4ab2-bda5-6d780eab3fd8)

![image](https://github.com/user-attachments/assets/f169bb60-14fe-460c-a0da-7fb1b58ab245)
