### ISSUE TITLE
Unknown Device Types Fire 8 Pro, Fire Stick, App for PC

### ISSUE THREAD

**Issue by jamesonuk** [chemelli74/aioamazondevices#245]
- A1RTAM01W29CUP - Is "Alexa App for PC` and shows up even though you can't actually use this any more.   I think these devices should actually be ignored
- ADVBD696BHNV5 - Fire TV Stick (Gen 1)
- A1TD5Z1R8IWBHA - Fire HD 8 (12th Gen)
- A15ERDAKK5HQQG - Sonos.   It is a Play 5 (first gen) but https://github.com/alandtse/alexa_media_player/blob/dev/custom_components/alexa_media/const.py and Amazon account just show it as Sonos so not sure if this covers more than one physical device type

**Comment by jamesonuk** [comment]
> Can you confirm the 2 notify entities works fine please ?

Possibly another issue to raise but I can't actually get the notify entities to work on any of my devices....

```
action: notify.send_message
data:
  message: test
target:
  entity_id: notify.study_dot_announce_dot_announce
```

seems to say it has worked but nothing gets announced.   I did see a HTTP 401 in the debug logs but I need a little time to look properly
